### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by sergeypushckin2018** [eppenga/Sunflow-Cryptobot#6]
Hello, can I specify a setting somewhere so that I can test your product on a demo account?

**Comment by eppenga** [comment]
Hi @sergeypushckin2018, the linkage depends on the API keys you supply. If you have API keys for a demo account Sunflow will automatically use the demo account.

**Comment by sergeypushckin2018** [comment]
Thank you!

**Comment by sergeypushckin2018** [comment]
Is this an error due to time or is there something wrong with the api key?api key for demo account


`qwe@qwe-virtual-machine:~/Sunflow-Cryptobot$ python3 sunflow.py

*************************
*** Sunflow Cryptobot ***
*************************

Symbol    : MNTUSDT
Spread    : 0.1 %
Profit    : 0.1 %
Limit     : 250


*** Preloading ***

2024-07-16 14:47:48.92 | MNTUSDT: preload.py: check_files: All folders and files checked

2024-07-16 14:47:48.92 | MNTUSDT: preload.py: get_ticker: session: get_tickers

2024-07-16 14:47:49.45 | MNTUSDT: preload.py: get_ticker: Initial ticker loaded

2024-07-16 14:47:49.45 | MNTUSDT: preload.py: get_info: session: get_instruments_info

2024-07-16 14:47:49.76 | MNTUSDT: database.py: load: Database contains 0 buy transactions and 0.00 MNT was bought

2024-07-16 14:47:49.76 | MNTUSDT: preload.py: check_orders: Checking all order on exchange

2024-07-16 14:47:49.76 | MNTUSDT: database.py: save: Database contains 0 buy transactions and 0.00 MNT was bought

2024-07-16 14:47:49.76 | MNTUSDT: orders.py: rebalance: session: get_wallet_balance

2024-07-16 14:47:50.31 | MNTUSDT: defs.py: log_error: Exception: API key is invalid. (ErrCode: 10003) (ErrTime: 14:47:50).
Request → GET https://api.bybit.com/v5/account/wallet-balance: accountType=UNIFIED&coin=MNT.

2024-07-16 14:47:50.31 | MNTUSDT: defs.py: log_error: *** Terminating Sunflow, error to severe! ***

2024-07-16 14:47:50.31 | MNTUSDT: defs.py: log_error: API key is invalid. (ErrCode: 10003) (ErrTime: 14:47:50).
Request → GET https://api.bybit.com/v5/account/wallet-balance: accountType=UNIFIED&coin=MNT.

Traceback (most recent call last):
  File "/home/qwe/Sunflow-Cryptobot/sunflow.py", line 636, in <module>
    if config.database_rebalance: all_buys = orders.rebalance(all_buys, info)
  File "/home/qwe/Sunflow-Cryptobot/orders.py", line 383, in rebalance
    equity_wallet = equity_safe(wallet['result']['list'][0]['coin'][0]['equity'])
KeyError: 'result'
`

**Comment by sergeypushckin2018** [comment]
`2024-07-16 14:56:29.70 | MNTUSDT: preload.py: get_ticker: {'time': 1721141789578, 'lastPrice': 0.7566, 'symbol': 'MNTUSDT'}
`
I don't understand what the problem is, I turned on debug, it showed what is above, I switched it to normal time and it coincides with my time on the computer. I also tried to change the time zones, it didn't help, I changed the time itself manually to the one that indicates and still the same error

**Comment by eppenga** [comment]
> `2024-07-16 14:56:29.70 | MNTUSDT: preload.py: get_ticker: {'time': 1721141789578, 'lastPrice': 0.7566, 'symbol': 'MNTUSDT'} ` I don't understand what the problem is, I turned on debug, it showed what is above, I switched it to normal time and it coincides with my time on the computer. I also tried to change the time zones, it didn't help, I changed the time itself manually to the one that indicates and still the same error

FYI Sunflow always works with UTC time.

**Comment by eppenga** [comment]
> Is this an error due to time or is there something wrong with the api key?api key for demo account
> 
> `qwe@qwe-virtual-machine:~/Sunflow-Cryptobot$ python3 sunflow.py
> 
> *** Sunflow Cryptobot ***
> 
> Symbol : MNTUSDT Spread : 0.1 % Profit : 0.1 % Limit : 250
> 
> *** Preloading ***
> 
> 2024-07-16 14:47:48.92 | MNTUSDT: preload.py: check_files: All folders and files checked
> 
> 2024-07-16 14:47:48.92 | MNTUSDT: preload.py: get_ticker: session: get_tickers
> 
> 2024-07-16 14:47:49.45 | MNTUSDT: preload.py: get_ticker: Initial ticker loaded
> 
> 2024-07-16 14:47:49.45 | MNTUSDT: preload.py: get_info: session: get_instruments_info
> 
> 2024-07-16 14:47:49.76 | MNTUSDT: database.py: load: Database contains 0 buy transactions and 0.00 MNT was bought
> 
> 2024-07-16 14:47:49.76 | MNTUSDT: preload.py: check_orders: Checking all order on exchange
> 
> 2024-07-16 14:47:49.76 | MNTUSDT: database.py: save: Database contains 0 buy transactions and 0.00 MNT was bought
> 
> 2024-07-16 14:47:49.76 | MNTUSDT: orders.py: rebalance: session: get_wallet_balance
> 
> 2024-07-16 14:47:50.31 | MNTUSDT: defs.py: log_error: Exception: API key is invalid. (ErrCode: 10003) (ErrTime: 14:47:50). Request → GET https://api.bybit.com/v5/account/wallet-balance: accountType=UNIFIED&coin=MNT.
> 
> 2024-07-16 14:47:50.31 | MNTUSDT: defs.py: log_error: *** Terminating Sunflow, error to severe! ***
> 
> 2024-07-16 14:47:50.31 | MNTUSDT: defs.py: log_error: API key is invalid. (ErrCode: 10003) (ErrTime: 14:47:50). Request → GET https://api.bybit.com/v5/account/wallet-balance: accountType=UNIFIED&coin=MNT.
> 
> Traceback (most recent call last): File "/home/qwe/Sunflow-Cryptobot/sunflow.py", line 636, in if config.database_rebalance: all_buys = orders.rebalance(all_buys, info) File "/home/qwe/Sunflow-Cryptobot/orders.py", line 383, in rebalance equity_wallet = equity_safe(wallet['result']['list'][0]['coin'][0]['equity']) KeyError: 'result' `

It seems it can't work with the demo account API key and it's also seems to have issues because the demo account has not equity (no money to trade with). Maybe it's easier if you still want to try it if you use a normal account and normal API key of Bybit. If you use XRPUSDC for example minimum order value is pretty low, around $ 1,50 per order.

**Comment by sergeypushckin2018** [comment]
Okay, thank you
